# Generated by Django 4.0.3 on 2023-07-24 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('employee_id', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='autovo',
            old_name='model_name',
            new_name='model',
        ),
        migrations.AddField(
            model_name='autovo',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('vip_status', models.PositiveSmallIntegerField()),
                ('vin', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
                ('appt_status', models.PositiveSmallIntegerField()),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='service_rest.technician')),
            ],
        ),
    ]
